version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing Cloud Custodian"
      - pip install -r requirements.txt
      - sed -i "s/{account_id}/${account_id}/" ./custodian-policies/accounts.yaml
  build:
    commands:
      - echo "Deploying Cloud Custodian Policies"
      - for i in $(find ./custodian-policies -maxdepth 1 -type f -name *.yml); do c7n-org run -c ./custodian-policies/accounts.yaml -s output -u $i; done